// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAHkvG8CHwhS2gquUUEB-8LmsFg8VV6E0',
    appId: '1:901947364556:web:02d65d48f7664c64d41e69',
    messagingSenderId: '901947364556',
    projectId: 'to-do-app-d5ded',
    authDomain: 'to-do-app-d5ded.firebaseapp.com',
    storageBucket: 'to-do-app-d5ded.appspot.com',
    measurementId: 'G-CV7CWRJ87G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXqwGTDF4cSITIBKeGqzKzNVYMEVq8THk',
    appId: '1:901947364556:android:a98903b20ec4bdecd41e69',
    messagingSenderId: '901947364556',
    projectId: 'to-do-app-d5ded',
    storageBucket: 'to-do-app-d5ded.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7VubG3LDY1D46xd98qCdEJ3NOoM1ILf4',
    appId: '1:901947364556:ios:75b7fe1d64d19233d41e69',
    messagingSenderId: '901947364556',
    projectId: 'to-do-app-d5ded',
    storageBucket: 'to-do-app-d5ded.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7VubG3LDY1D46xd98qCdEJ3NOoM1ILf4',
    appId: '1:901947364556:ios:381f25eedfe59da8d41e69',
    messagingSenderId: '901947364556',
    projectId: 'to-do-app-d5ded',
    storageBucket: 'to-do-app-d5ded.appspot.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
